.github/workflows/ci.yml
`setup-java` now takes care of caching.
This simplifies the workflow.
=> Update checkout and setup-java actions

project/plugins.sbt
We have scala steward providing us with pull request, we no longer need `sbt-updates` plugin
See: https://github.com/VirtusLab/scala-steward-repos/pull/234
=> Remove sbt-updates

.scala-steward.conf
We are not interested in scala steward updates for flink itself, because we are cross building for multiple versions.
To prevent more like
* #20
in the future
=> Ignore scala steward for flink itself

.github/workflows/ci.yml, build.sbt, release.sh, src/test/scala/org/apache/flinkx/api/ExampleTest.scala
=> flink-1-18-support

src/main/scala/org/apache/flinkx/api/serializer/MappedSerializer.scala, src/test/scala/org/apache/flinkx/api/MappedTypeInfoTest.scala
Should solve https://github.com/flink-extended/flink-scala-api/issues/81
I am not entirely sure if the spec spinning the whole execution environment is supposed to be under the mapped type info test, but it felt like the right place because of the problem scope. Let me know if something needs fixing.
=> Make TypeMapper trait serializable

src/main/scala/org/apache/flinkx/api/serializers.scala
`JBigDecimal` was marked as unused due to `java.math.BigInteger` import, make it consistent with other Java types.
=> Use consistent JBigInteger alias

build.sbt, src/test/scala/org/apache/flinkx/api/CoGroupedStreamsTest.scala, src/test/scala/org/apache/flinkx/api/DataStreamTest.scala, src/test/scala/org/apache/flinkx/api/ExampleTest.scala, src/test/scala/org/apache/flinkx/api/IntegrationTest.scala, src/test/scala/org/apache/flinkx/api/IntegrationTestSink.scala, src/test/scala/org/apache/flinkx/api/JoinedStreamsTest.scala, src/test/scala/org/apache/flinkx/api/MappedTypeInfoTest.scala, src/test/scala/org/apache/flinkx/api/StreamExecutionEnvironmentTest.scala
Addresses:
- https://github.com/flink-extended/flink-scala-api/issues/70
- https://github.com/flink-extended/flink-scala-api/issues/91
The key change is the introduction of `IntegrationTest` and `IntegrationTestSink` which are used across the whole testing suite instead of obtaining the execution environment from _somewhere_.
Given that the example test was failing and it was the only one using `.executeAndCollect()`, I suspected it could be the cause for floppiness, flink [recommends](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/testing/#testing-flink-jobs) building a custom sink operator to test job outputs and I've done exactly that by implementing `IntegrationTestSink` class. I've been using exactly this kind of sink function and have never had an issue …
=> Stabilize tests

src/test/scala/org/apache/flinkx/api/IntegrationTest.scala
I've noticed that after my change test times increased. Previously, example test would call `cluster.before()` and `cluster.after()` in the before/after ALL test hook, not before each. Using it in the all lifecycle is correct because it will setup and tear down the whole cluster, which is recommended by the documentation https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/testing/
> Prefer @ClassRule over @Rule so that multiple tests can share the same Flink cluster. Doing so saves a significant amount of time since the startup and shutdown of Flink clusters usually dominate the execution time of the actual tests.
=> Correct flink test cluster lifecycle methods

.github/workflows/ci.yml
Addresses the https://github.com/flink-extended/flink-scala-api/issues/99#issuecomment-1979076639, this will allow implementing async i/o retry policy given the minimum version bump.
=> Align ci and release versions

src/main/scala/org/apache/flinkx/api/AsyncDataStream.scala, src/test/scala/org/apache/flinkx/api/AsyncDataStreamTest.scala
Addresses https://github.com/flink-extended/flink-scala-api/issues/99 and requires https://github.com/flink-extended/flink-scala-api/pull/100 to be merged first to deprecate 1.15 support in CI, release builds.
This change adds `WithRetry` versions to the currently existing async stream helpers, it uses the already-built official retry strategy interface, which will allow to use of already pre-built retry strategies.
~~I see that the async wrapper had no test strategies, do we need one? Official client is covered https://github.com/apache/flink/blob/master/flink-streaming-scala/src/test/scala/org/apache/flink/streaming/api/scala/AsyncDataStreamITCase.scala~~
I've used specs from original flink scala library as a source and adapted the implementation.
=> Add async i/o with retry support

src/main/java/org/apache/flink/api/serializer/ScalaCaseClassSerializerSnapshot.java, src/test/scala/org/apache/flinkx/api/SerializerSnapshotTest.scala
In Flink session-mode clusters, `resolveSchemaCompatibility` returns `INCOMPATIBLE` even for identical case classes (even without any recompiles or reuploads to the cluster). This is due to way Flink state restore works, resulting in the same class being loaded multiple times in different classloaders.
Steps to reproduce:
1. Start Flink cluster in session-mode.
2. Start some job with single operator that saves case class in the state.
3. Wait for the checkpoint.
4. Kill the job.
5. Restart the job from the checkpoint - Flink fails to init the operator with the case class in the state.
To mitigate the issue, I've changed the outer check from direct class equality, which in reality is just reference equality, to class name comparison.
=> Fix case class serializer snapshot compatibility

.github/workflows/ci.yml, build.sbt
Reverts flink-extended/flink-scala-api#103
Keeping LTS version of Scala 3.3.x rather than go for 3.4.
See more here: https://www.scala-lang.org/blog/2024/02/29/scala-3.4.0-and-3.3.3-released.html
=> Revert "Update scala3-compiler, scala3-library to 3.4.1"

src/main/scala/org/apache/flinkx/api/serializer/CaseClassSerializer.scala, src/main/scala/org/apache/flinkx/api/typeinfo/CollectionTypeInformation.scala, src/main/scala/org/apache/flinkx/api/typeinfo/CoproductTypeInformation.scala, src/main/scala/org/apache/flinkx/api/typeinfo/ProductTypeInformation.scala, src/main/scala/org/apache/flinkx/api/typeinfo/SimpleTypeInformation.scala, src/test/scala/org/apache/flinkx/api/SerializerTest.scala
Additional change for some of the TypeInfos to call duplicate serializers when they are not immutable.
FYI @sonowz
=> Call duplicate when type is not immutable

.github/workflows/ci.yml, README.md, build.sbt, modules/scala-api/src/main/scala-3/org/apache/flinkx/api/TaggedDerivation.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/ClosureCleaner.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/ConnectedStreams.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/DataStream.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/KeyedStream.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/StreamExecutionEnvironment.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/extensions/impl/acceptPartialFunctions/OnConnectedStream.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/extensions/impl/acceptPartialFunctions/OnDataStream.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/function/util/ScalaAllWindowFunction.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/function/util/ScalaProcessWindowFunctionWrapper.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/function/util/ScalaWindowFunction.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/typeinfo/CaseClassTypeInfo.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/typeinfo/EitherTypeInfo.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/typeinfo/OptionTypeInfo.scala
=> drop scala 2.12 support, add deprecations, remove returns usage

README.md
A proposal to add a `State` section under `Migration` of the readme to warn about risk of state descriptor misuse described in issue #187.
=> #187 Documents state migration

README.md
As describe in the issue and this comment https://github.com/flink-extended/flink-scala-api/issues/187#issuecomment-2561103102, here is a proposal to add more details of interactions between Scala and Kryo and explain the case where the duplication of case objects can occur.
**First** point of comment is addressed by adding some context:
```diff
- has no silent fallback to Kryo: it will just fail the compilation in a case when serializer cannot be made
+ `TypeInformation` derivation macro has no silent fallback to Kryo: it will just fail the compilation in a case when serializer cannot be made
```
**Second** point:
- add explanations in "Supported Flink versions" section where the suggestion of removing `flink-scala` dependency was made.
- Add more details in new "Interaction with Flink's …
=> #187 Add details on interactions between Scala and Kryo

modules/scala-api/src/main/scala/org/apache/flinkx/api/conv.scala
Allows to pass Scala API wrappers as Java types
=> add implicit converters to Java counterparts

modules/scala-api/src/main/scala/org/apache/flinkx/api/DataStream.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/StreamExecutionEnvironment.scala
add more wrappers to Scala API
=> extend Scala API

README.md, modules/scala-api/src/main/scala/org/apache/flinkx/api/StreamExecutionEnvironment.scala, modules/scala-api/src/main/scala/org/apache/flinkx/api/typeinfo/FailFastTypeInfoFactory.scala, modules/scala-api/src/test/scala/org/apache/flinkx/api/StreamExecutionEnvironmentTest.scala
Here is the PR discussed in issue #187.
About your questions in the issue:
1. Yes, there is no difference between Scala versions, it's just a matter of Flink configuration.
2. As you can see in the PR, `pipeline.serialization-config` property do nothing before Flink 1.19, so there is no need to drop support. When 1.18 support will be dropped, we'll be able to use `PipelineOptions.SERIALIZATION_CONFIG` constant and simplify the test.
Is the modification in the readme and explanations given by the exception clear enough to you? 
Thanks
=> feat(#187): fail-fast on Scala type resolution with Class

modules/scala-api/src/main/scala-2/org/apache/flinkx/api/LowPrioImplicits.scala, modules/scala-api/src/main/scala-3/org/apache/flinkx/api/LowPrioImplicits.scala, modules/scala-api/src/main/scala-3/org/apache/flinkx/api/TypeTag.scala, modules/scala-api/src/main/scala-3/org/apache/flinkx/api/TypeTagMacro.scala, modules/scala-api/src/test/scala-2/org/apache/flinkx/api/GenericCaseClassScala2Test.scala, modules/scala-api/src/test/scala-3/org/apache/flinkx/api/GenericCaseClassScala3Test.scala
This PR is a work in progress to allow to reproduce the issue described #206 and to propose a fix for Scala 2.
The root cause of the problem comes from magnolia `TypeName` used as cache key: `TypeName.typeArguments` are not resolved with the concrete types (`Basket[Cat]`) but keep referencing the unresolved abstract types (`Basket[A]`).
In Scala 2, the fix is simply to replace usage of magnolia `TypeName` in favor of `TypeTag` which resolve correctly type parameters to concrete types.
Unfortunately, this fix is not working in Scala 3 because there is no `TypeTag` and the one you are creating yourself seems to not have enough information.
I don't know the best way to fix it for Scala 3, maybe by improving your `TypeTag` implementation or maybe by finding more type parameters information …
=> #206 Reproduce derivation of generic case class issue & fix for Scala 2

README.md, modules/scala-api/src/main/scala/org/apache/flinkx/api/StreamExecutionEnvironment.scala
Here is the fix for the problems described in [this](https://github.com/flink-extended/flink-scala-api/issues/187#issuecomment-2668268134) comment.
Thanks
=> # 187 Fix registration of fast-fast factory

modules/scala-api/src/main/scala/org/apache/flinkx/api/typeinfo/UnitTypeInformation.scala
Hi,
I came across a runtime error when using `Unit` type as a key of ConnectedStream. ([Flink source](https://github.com/apache/flink/blob/ef09e1716924d1e6ed64bfc273859f2de979b027/flink-runtime/src/main/java/org/apache/flink/streaming/api/datastream/ConnectedStreams.java#L502))
When compared to others like `OptionTypeInfo`, I found out that `UnitTypeInformation` has wrong equality check logic.
=> Fix UnitTypeInformation equality logic

modules/flink-1-api/src/test/scala-3/org/apache/flinkx/api/GenericCaseClassScala3Test.scala, modules/flink-common-api/src/main/scala-3/org/apache/flinkx/api/TypeTagMacro.scala
A potential solution for #242, changes isCachableExpr to recursively inspect the arguments to see if there's a generic parameter.
There may well be better way to do this, I'm not too familiar with scala 3 macros.
=> Don't cache nested classes with generic type parameters

modules/flink-1-api/src/test/scala/org/apache/flinkx/api/SerializerSnapshotTest.scala, modules/flink-1-api/src/test/scala/org/apache/flinkx/api/TestUtils.scala, modules/flink-2-api/src/main/scala/org/apache/flinkx/api/serializer/CollectionSerializerSnapshot.scala, modules/flink-2-api/src/main/scala/org/apache/flinkx/api/serializer/CoproductSerializer.scala, modules/flink-2-api/src/main/scala/org/apache/flinkx/api/serializer/MapSerializer.scala, modules/flink-2-api/src/main/scala/org/apache/flinkx/api/serializer/MappedSerializer.scala, modules/flink-2-api/src/main/scala/org/apache/flinkx/api/serializer/ScalaCaseObjectSerializer.scala, modules/flink-2-api/src/test/scala/org/apache/flinkx/api/serializer/CollectionSerializerSnapshotTest.scala, modules/flink-2-api/src/test/scala/org/apache/flinkx/api/serializer/MapSerializerSnapshotTest.scala
As designed in the issue https://github.com/flink-extended/flink-scala-api/issues/240, here is my proposal to handle state evolution without breaking state compatibility.
`ScalaCaseObjectSerializer` has not the issue because it doesn't serialize serializers, but I added `MapSerializer` in addition of the previous list.
Write a test that reproduces the issue and shows this PR fixes it was hard, please have a look at `MapSerializerSnapshotTest`. I didn't write a test for each serializer snapshot, but the logic is the same.
I was surprised to see no tests for Flink 2, I created the root test folder, but maybe tests for Flink 1 should be duplicated for Flink 2 also?
As said in the issue, I can also do these changes for Flink 1, but it will break the state compatibility. …
=> Handle state evolution without breaking state compatibility

modules/flink-1-api/src/main/scala-2/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-1-api/src/main/scala-3/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-1-api/src/test/scala/org/apache/flinkx/api/SerializerTest.scala, modules/flink-2-api/src/main/scala-2/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-2-api/src/main/scala-3/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-common-api/src/main/scala/org/apache/flinkx/api/util/ClassUtil.scala, modules/flink-common-api/src/test/scala/org/apache/flinkx/api/util/ClassUtilTest.scala
As I said in this comment https://github.com/flink-extended/flink-scala-api/pull/248#discussion_r2077745972 I found a bug in the detection of the immutability of a case class with private field.
Under some circonstances (I'm not 100% sure) for exemple when a case class with private field is declared after an object, the field name in the java class takes the name `className$$fieldName` instead of the field name only.
The fix complexifies the field lookup to also handle this case.
=> Fix detection of immutability in case class with private field

README.md, modules/flink-1-api/src/main/scala-2/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-1-api/src/main/scala-3/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-1-api/src/test/scala/org/apache/flinkx/api/SchemaEvolutionTest.scala, modules/flink-1-api/src/test/scala/org/apache/flinkx/api/SerializerTest.scala, modules/flink-2-api/src/main/scala-2/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-2-api/src/main/scala-3/org/apache/flinkx/api/LowPrioImplicits.scala, modules/flink-common-api/src/main/scala/org/apache/flinkx/api/serializer/CaseClassSerializer.scala, modules/flink-common-api/src/main/scala/org/apache/flinkx/api/serializer/nullable.scala
As a complement for the previous PR (https://github.com/flink-extended/flink-scala-api/pull/265) to handle nullability (https://github.com/flink-extended/flink-scala-api/issues/264), I propose this PR to handle null fields in case class.
The idea is to allow a `@nullable` annotation on case class fields that is handled at case class serializer creation in `LowPrioImplicits.join()`.
It seems quite easy to implement thanks to improvement made in previous PR (it relies on changes in `ConstructorCompat`).
However, nullable field handling can be done in different ways:
- Create our own `@nullable` annotation (currently in this PR).
- Don't create `@nullable` annotation and always wrap fields in `NullableSerializer`.
- Accept external annotation like …
=> feature: handle null field in case class
